baseURL: /
languageCode: en-us
title: dim radio
theme: hugo-ink
paginate: 5
copyright: © Copyright notice
pygmentsstyle: vs
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
googleAnalytics: UA-123-45
disqusShortname: pinkr1ver
params:
  avatar: https://avatars.githubusercontent.com/u/50662650?v=4
  disableDisqusTypes: page
  featherIconsCDN: yes
  mode: auto
  social:
    - icon: github
      name: Github
      url: https://github.com/PinkR1ver
    - icon: mail
      name: Mail
      url: mailto:pinkr1veroops@gmail.com
    - icon: twitter
      name: twitter
      url: https://twitter.com/PinkR1ver
    - icon: instagram
      name: Instagram
      url: https://www.instagram.com/pinkcred1t/
    - icon: rss
      name: RSS
      url: /index.xml
  subtitle: Stu(dying) :D
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
taxonomies:
  tag: tags
